apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl  # base64 encoded "your-jwt-secret-key-here"