server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
        - id: cart-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/cart/**
        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/notifications/**
        - id: review-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/reviews/**
        - id: analytics-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/analytics/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG