server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: http://inventory-service:8083
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://payment-service:8085
          predicates:
            - Path=/api/payments/**
        - id: cart-service
          uri: http://cart-service:8086
          predicates:
            - Path=/api/cart/**
        - id: notification-service
          uri: http://notification-service:8087
          predicates:
            - Path=/api/notifications/**
        - id: review-service
          uri: http://review-service:8088
          predicates:
            - Path=/api/reviews/**
        - id: analytics-service
          uri: http://analytics-service:8089
          predicates:
            - Path=/api/analytics/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"